# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    Contents: '**/*.dacpac'
    TargetFolder: '$(build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Azure subscription 1(a38cf16c-8668-4313-b4fa-8e91aeeabe24)'
    AuthenticationType: 'server'
    ServerName: 'dev-secudapp.database.windows.net,1433'
    DatabaseName: 'secudapp'
    SqlUsername: 'chungsiksong'
    SqlPassword: 'SimpleLife2022'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(agent.BuildDirectory)/SecuDapp.Database/drop/bin/release/SecuDapp.Database.dacpac'
    IpDetectionMethod: 'AutoDetect'